### PR TITLE
fix: sidebar emoji is out of sync

### LINKED ISSUE #45: sidebar emoji is out of sync
I've noticed that sometimes `app/routes/_app+/_exercises+/_layout.tsx` runs before `/set-playground` action end.
In this cases playground emoji is out of sync.

I've tried to add `shouldRevalidate` in `app/routes/_app+/_exercises+/_layout.tsx` but it didn't helped, it appear that it is also triggered before the action ends 

I did not find any reference in Remix to a way to asynchronous trigger loader after action from other route completed

_Originally posted by @onemen in https://github.com/epicweb-dev/kcdshop/issues/36#issuecomment-1512595859_

### PR DESCRIPTION
**Pull request by onemen**
closes #45

### CODE REVIEW

File: packages/workshop-app/app/routes/_app+/_exercises+/_layout.tsx [hunk 1]
```diff
@@ -24,33 +20,30 @@ export async function loader({ request }: DataFunctionArgs) {
...
+				title,
+				name,
 			})),
-			playgroundAppName,
-		},
-		{
-			headers: {
-				'Cache-Control': 'public, max-age=300',
-				Vary: 'Cookie',
-				'Server-Timing': getServerTimeHeader(timings),
```
Comment (kentcdodds) [inline packages/workshop-app/app/routes/_app+/_exercises+/_layout.tsx:50]: We need to keep this header so we can see server timings in the browser.

Comment (onemen) [reply packages/workshop-app/app/routes/_app+/_exercises+/_layout.tsx:50]: i can remove only `'Cache-Control': 'public, max-age=300',`

**Review by kentcdodds — APPROVED** [review]
Thanks!
